# Homelab Kubernetes Infrastructure
# Main helmfile configuration

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600
  createNamespace: true
  atomic: false

environments:
  default:
    values:
      - environments/default.yaml

repositories:
  # CNI & Networking
  - name: cilium
    url: https://helm.cilium.io
  - name: metallb
    url: https://metallb.github.io/metallb

  # Storage
  - name: longhorn
    url: https://charts.longhorn.io

  # Secrets Management
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: external-secrets
    url: https://charts.external-secrets.io

  # GitOps
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: chartmuseum
    url: https://chartmuseum.github.io/charts

  # Service Mesh
  - name: linkerd
    url: https://helm.linkerd.io/stable

  # Observability
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

  # Ingress
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts

  # Utilities
  - name: stakater
    url: https://stakater.github.io/stakater-charts
  - name: kubereboot
    url: https://kubereboot.github.io/charts

  # Certificate Management
  - name: jetstack
    url: https://charts.jetstack.io

---
# Load all release files
helmfiles:
  # Cluster Foundation
  # NOTE: Cilium requires k3s with --flannel-backend=none
  # Uncomment when using dedicated k3s cluster
  # - path: releases/01-cilium.yaml
  # NOTE: MetalLB skipped for local Colima - use port-forwarding instead
  # - path: releases/02-metallb.yaml

  # Storage
  # NOTE: Longhorn skipped for local Colima - using k3s local-path storage
  # - path: releases/03-longhorn.yaml

  # Certificate Management (needed before secrets/mesh)
  - path: releases/04-cert-manager.yaml

  # Secrets Management
  - path: releases/05-vault.yaml
  - path: releases/06-external-secrets.yaml

  # GitOps
  - path: releases/07-argocd.yaml
  - path: releases/08-chartmuseum.yaml

  # Service Mesh
  - path: releases/09-linkerd-crds.yaml
  - path: releases/10-linkerd-control-plane.yaml
  - path: releases/11-linkerd-viz.yaml

  # Observability - Operator & Collection
  # NOTE: Skipped for now - requires additional OTel config
  # - path: releases/12-otel-operator.yaml
  # - path: releases/13-otel-collector.yaml

  # Observability - Storage Backends
  # NOTE: Enable after OTel operator is working
  # - path: releases/14-tempo.yaml
  # - path: releases/15-pyroscope.yaml
  # - path: releases/16-loki.yaml
  # - path: releases/17-mimir.yaml

  # Observability - UI
  # NOTE: Enable after backends are working
  # - path: releases/18-grafana.yaml

  # Ingress
  # NOTE: Requires Cloudflare tunnel setup
  # - path: releases/19-cloudflared.yaml

  # Utilities
  - path: releases/20-reloader.yaml
  - path: releases/21-kured.yaml
